apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app.kubernetes.io/name: angular
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: angular
      app.kubernetes.io/component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: angular
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: angular
          image: jorgerap1997/frontend:latest
          command: ["/bin/sh", "-c", "sleep 40 && npm start"]
          # args:
          #   - --bind_ip
          #   - 0.0.0.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 4200
