apiVersion: v1
kind: Service
metadata:
  name: angular
  labels:
    app.kubernetes.io/name: angular
    app.kubernetes.io/component: frontend
spec:
  type: LoadBalancer
  # type: ClusterIP
  ports:
  - port: 4200
    targetPort: 4200
  selector:
    app.kubernetes.io/name: angular
    app.kubernetes.io/component: frontend